import { LineEdit } from "std-widgets.slint";

export component Browser inherits Window {
	in-out property <string> url: "https://abghim.github.io";
	callback go(string);

	title: "airBrowse";
 	preferred-width: 1440px;
  	preferred-height: 844px;

  	max-width: 1440px;
   	max-height: 844px;


   	min-width: 720px;
    min-height: 400px;

	VerticalLayout {
		Rectangle {
			height: 40px;
			Rectangle {
				x: 8px; y: 6px; width: parent.width - 16px; height: parent.height - 12px;
				LineEdit {
					text: root.url;
					placeholder-text: "Url or search query";
					accepted => {
						root.url = self.text;
						root.go(self.text);
					}
				}
			}
		}

		Rectangle {
			background: #000000;
		}
	}
}
